code --install-extension Extensions installed on WSL: Ubuntu:
code --install-extension bierner.github-markdown-preview
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bierner.markdown-yaml-preamble
code --install-extension cbuelter.vscode-toggle-max-editor
code --install-extension codezombiech.gitignore
code --install-extension cyansprite.smoothscroll
code --install-extension davidanson.vscode-markdownlint
code --install-extension esbenp.prettier-vscode
code --install-extension gera2ld.markmap-vscode
code --install-extension ibm.output-colorizer
code --install-extension intellsmi.comment-translate
code --install-extension ionutvmi.path-autocomplete
code --install-extension janisdd.vscode-edit-csv
code --install-extension jebbs.plantuml
code --install-extension kevinrose.vsc-python-indent
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.live-server
code --install-extension mushan.vscode-paste-image
code --install-extension naumovs.color-highlight
code --install-extension nickdemayo.vscode-json-editor
code --install-extension phoihos.csv-to-md-table
code --install-extension pkief.material-icon-theme
code --install-extension richie5um2.vscode-sort-json
code --install-extension shardulm94.trailing-spaces
code --install-extension takumii.markdowntable
code --install-extension usernamehw.errorlens
code --install-extension vincaslt.highlight-matching-tag
code --install-extension xadillax.viml
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
